spring:
  application:
    name: ecommerce-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce
      database: ecommerce
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    clean-disabled: false

